/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.t2;

import org.junit.jupiter.api.Test;


class AppTest {
    @ Test void main() {
        App app = new App();
        app.main(null);
    }
}
